"""Canonical Bible book-name mapping.

Shared home for book-name normalization so analyses don't each carry their own
copy. This currently holds the full-English-name -> 3-letter Paratext/USFM code
map used by the English analyses. Other book tables that predate this module
(``els.critical.BOOK_TO_SBL``, ``els.corpus.NT_BOOK_ORDER`` /
``OT_BOOK_ORDER``, ``els.morphology.MORPHGNT_BOOKS``) target different output
vocabularies and should migrate here over time.
"""

from __future__ import annotations


# Full English book name -> 3-letter Paratext/USFM code. Names not present are
# returned unchanged by ``canonical_book_code`` so already-coded refs pass
# through.
ENGLISH_NAME_TO_CODE: dict[str, str] = {
    "Genesis": "GEN",
    "Exodus": "EXO",
    "Leviticus": "LEV",
    "Numbers": "NUM",
    "Deuteronomy": "DEU",
    "Joshua": "JOS",
    "Judges": "JDG",
    "Ruth": "RUT",
    "1 Samuel": "1SA",
    "2 Samuel": "2SA",
    "1 Kings": "1KI",
    "2 Kings": "2KI",
    "1 Chronicles": "1CH",
    "2 Chronicles": "2CH",
    "Ezra": "EZR",
    "Nehemiah": "NEH",
    "Esther": "EST",
    "Job": "JOB",
    "Psalms": "PSA",
    "Psalm": "PSA",
    "Proverbs": "PRO",
    "Ecclesiastes": "ECC",
    "Song of Solomon": "SNG",
    "Song of Songs": "SNG",
    "Isaiah": "ISA",
    "Jeremiah": "JER",
    "Lamentations": "LAM",
    "Ezekiel": "EZK",
    "Daniel": "DAN",
    "Hosea": "HOS",
    "Joel": "JOL",
    "Amos": "AMO",
    "Obadiah": "OBA",
    "Jonah": "JON",
    "Micah": "MIC",
    "Nahum": "NAM",
    "Habakkuk": "HAB",
    "Zephaniah": "ZEP",
    "Haggai": "HAG",
    "Zechariah": "ZEC",
    "Malachi": "MAL",
    "Matthew": "MAT",
    "Mark": "MRK",
    "Luke": "LUK",
    "John": "JHN",
    "Acts": "ACT",
    "Romans": "ROM",
    "1 Corinthians": "1CO",
    "2 Corinthians": "2CO",
    "Galatians": "GAL",
    "Ephesians": "EPH",
    "Philippians": "PHP",
    "Colossians": "COL",
    "1 Thessalonians": "1TH",
    "2 Thessalonians": "2TH",
    "1 Timothy": "1TI",
    "2 Timothy": "2TI",
    "Titus": "TIT",
    "Philemon": "PHM",
    "Hebrews": "HEB",
    "James": "JAS",
    "1 Peter": "1PE",
    "2 Peter": "2PE",
    "1 John": "1JN",
    "2 John": "2JN",
    "3 John": "3JN",
    "Jude": "JUD",
    "Revelation": "REV",
}


def canonical_book_code(book: str) -> str:
    """Return the 3-letter code for a full English book name.

    Unknown values (including already-coded inputs like ``"JHN"``) are returned
    unchanged.
    """
    return ENGLISH_NAME_TO_CODE.get(book, book)


NT_BOOK_ORDER = {
    "Matt": 1,
    "Mark": 2,
    "Luke": 3,
    "John": 4,
    "Acts": 5,
    "Rom": 6,
    "1Cor": 7,
    "2Cor": 8,
    "Gal": 9,
    "Eph": 10,
    "Phil": 11,
    "Col": 12,
    "1Thess": 13,
    "2Thess": 14,
    "1Tim": 15,
    "2Tim": 16,
    "Titus": 17,
    "Phlm": 18,
    "Heb": 19,
    "Jas": 20,
    "1Pet": 21,
    "2Pet": 22,
    "1John": 23,
    "2John": 24,
    "3John": 25,
    "Jude": 26,
    "Rev": 27,
}


OT_BOOK_ORDER = {
    "Gen": 1,
    "Exod": 2,
    "Lev": 3,
    "Num": 4,
    "Deut": 5,
    "Josh": 6,
    "Judg": 7,
    "1Sam": 8,
    "2Sam": 9,
    "1Kgs": 10,
    "2Kgs": 11,
    "Isa": 12,
    "Jer": 13,
    "Ezek": 14,
    "Hos": 15,
    "Joel": 16,
    "Amos": 17,
    "Obad": 18,
    "Jonah": 19,
    "Mic": 20,
    "Nah": 21,
    "Hab": 22,
    "Zeph": 23,
    "Hag": 24,
    "Zech": 25,
    "Mal": 26,
    "Ps": 27,
    "Prov": 28,
    "Job": 29,
    "Song": 30,
    "Ruth": 31,
    "Lam": 32,
    "Eccl": 33,
    "Esth": 34,
    "Dan": 35,
    "Ezra": 36,
    "Neh": 37,
    "1Chr": 38,
    "2Chr": 39,
}


BOOK_TO_SBL = {
    "MAT": "Matt",
    "MRK": "Mark",
    "LUK": "Luke",
    "JHN": "John",
    "ACT": "Acts",
    "ROM": "Rom",
    "1CO": "1Cor",
    "2CO": "2Cor",
    "GAL": "Gal",
    "EPH": "Eph",
    "PHP": "Phil",
    "COL": "Col",
    "1TH": "1Thess",
    "2TH": "2Thess",
    "1TI": "1Tim",
    "2TI": "2Tim",
    "TIT": "Titus",
    "PHM": "Phlm",
    "HEB": "Heb",
    "JAS": "Jas",
    "1PE": "1Pet",
    "2PE": "2Pet",
    "1JN": "1John",
    "2JN": "2John",
    "3JN": "3John",
    "JUD": "Jude",
    "REV": "Rev",
    "Matthew": "Matt",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Acts",
    "Romans": "Rom",
    "1 Corinthians": "1Cor",
    "2 Corinthians": "2Cor",
    "Galatians": "Gal",
    "Ephesians": "Eph",
    "Philippians": "Phil",
    "Colossians": "Col",
    "1 Thessalonians": "1Thess",
    "2 Thessalonians": "2Thess",
    "1 Timothy": "1Tim",
    "2 Timothy": "2Tim",
    "Titus": "Titus",
    "Philemon": "Phlm",
    "Hebrews": "Heb",
    "James": "Jas",
    "1 Peter": "1Pet",
    "2 Peter": "2Pet",
    "1 John": "1John",
    "2 John": "2John",
    "3 John": "3John",
    "Jude": "Jude",
    "Revelation": "Rev",
}


MORPHGNT_BOOKS = {
    "01": "Matt",
    "02": "Mark",
    "03": "Luke",
    "04": "John",
    "05": "Acts",
    "06": "Rom",
    "07": "1Cor",
    "08": "2Cor",
    "09": "Gal",
    "10": "Eph",
    "11": "Phil",
    "12": "Col",
    "13": "1Thess",
    "14": "2Thess",
    "15": "1Tim",
    "16": "2Tim",
    "17": "Titus",
    "18": "Phlm",
    "19": "Heb",
    "20": "Jas",
    "21": "1Pet",
    "22": "2Pet",
    "23": "1John",
    "24": "2John",
    "25": "3John",
    "26": "Jude",
    "27": "Rev",
}
