name = "unfoldingWord Hebrew Bible"
language = "hebrew"

[[sources]]
name = "UHB"
format = "csv"
path = "../data/processed/unfoldingword/hbo_uhb.csv"
text_column = "text"
ref_column = "ref"
book_column = "book"
chapter_column = "chapter"
verse_column = "verse"
