name = "Local Private English Message"
language = "english"

[[sources]]
name = "MSG"
format = "csv"
path = "../data/private/english/msg.csv"
text_column = "text"
ref_column = "ref"
book_column = "book"
chapter_column = "chapter"
verse_column = "verse"
