name = "Local Private English AMPC"
language = "english"

[[sources]]
name = "AMPC"
format = "csv"
path = "../data/private/english/ampc.csv"
text_column = "text"
ref_column = "ref"
book_column = "book"
chapter_column = "chapter"
verse_column = "verse"
