name = "Local Private English NLT"
language = "english"

[[sources]]
name = "NLT"
format = "csv"
path = "../data/private/english/nlt.csv"
text_column = "text"
ref_column = "ref"
book_column = "book"
chapter_column = "chapter"
verse_column = "verse"
